openmcp-project/controller-utils

- .github/workflows/release.yaml
> Fix issues with release action

- CONTRIBUTING.md
- README.md
This PR fixes the code of conduct in the CONTRIBUTING.md like already done in [openmcp-project/project-workspace-operator@`e8f5daa` (#5)](https://github.com/openmcp-project/project-workspace-operator/pull/5/commits/e8f5daa34d30d15af73c5847889191f9e9d22443). Additionally, this PR fixes a typo in the README.
> docs(contributing): update code of conduct

- .gitignore
- README.md
- pkg/conditions/conditions.go
- pkg/conditions/suite_test.go
- pkg/conditions/updater.go
- pkg/conditions/updater_test.go
Added a library for condition management.
> add condition management library

- README.md
- pkg/clusters/cluster.go
- pkg/controller/utils.go
- pkg/logging/config.go
Adds some helper functions to make setting up `Client` and `Cluster` representations for k8s clusters easier. See README for instructions.
> Multi-Cluster utilities

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- README.md
- pkg/clusters/cluster.go
- pkg/conditions/updater.go
- pkg/conditions/updater_test.go
- pkg/controller/annotation_label.go
- pkg/controller/predicates.go
- pkg/controller/status_updater.go
- pkg/controller/status_updater_test.go
- pkg/controller/testdata/test-02/co_nostatus.yaml
- pkg/controller/testdata/test-02/co_status.yaml
- pkg/controller/utils.go
- pkg/errors/reasonable_error.go
- pkg/testing/matchers/conditions.go
- pkg/testing/utils.go
Adds library functions that assist with updating a k8s resource's status, as long as it follows a specific pattern.
Also includes some changes I made while working on the Gardener ClusterProvider.
> Add status updater

- pkg/controller/utils.go
- pkg/controller/utils_test.go
First commit adds some unit-testing for the existing sha1 implementation. Second commit switches to sha256 and clarifies which kind of Kubernetes compliance we are achieving
```feature user
NONE
```
> use fips-compliant hash for K8sNameHash func

- pkg/clusters/cluster.go
There are use-cases in which the default options for `client.Client` and `cluster.Cluster` with just the `Scheme` set are not sufficient. This PR introduces the possibility to arbitrarily modify both options when working with the `clusters` package.
As a side effect, calling `InitializeRESTConfig()` and `InitializeClient(...)` multiple times is now not a no-op anymore, but actually re-loads the config and re-creates cluster and client, respectively.
Required for the [ClusterProvider: Gardener](https://github.com/openmcp-project/cluster-provider-gardener).
> add option to inject options for Cluster and Client

- README.md
- pkg/threads/manager.go
- pkg/threads/manager_test.go
- pkg/threads/suite_test.go
In the [ClusterProvider: Gardener](https://github.com/openmcp-project/cluster-provider-gardener), we add watches to clusters during runtime, which essentially works by calling `Start(...)` on that cluster's cache. This is a blocking method, so it has to run in a new go routine, and it can return an error, so we cannot simply do `go cache.Start(...)`, because then we would not notice if the watch failed somehow.
This means that we need slightly more complex logic to handle the multiple go routines. Using the `errgroup` package's `Wait()` method doesn't work either, because that one too blocks and returns an error, and furthermore stops when all go routines in the group have finished, which doesn't fit our use case, where having zero watches is …
> add small thread management library

- README.md
- pkg/resources/clusterrole.go
- pkg/resources/clusterrole_test.go
- pkg/resources/clusterrolebinding.go
- pkg/resources/clusterrolebinding_test.go
- pkg/resources/configmap.go
- pkg/resources/configmap_test.go
- pkg/resources/crd.go
- pkg/resources/crd_test.go
- pkg/resources/metadata.go
- pkg/resources/mutator.go
- pkg/resources/mutator_test.go
- pkg/resources/namespace.go
- pkg/resources/namespace_test.go
- pkg/resources/resources_suite_test.go
- pkg/resources/role.go
- pkg/resources/role_test.go
- pkg/resources/rolebinding.go
- pkg/resources/rolebinding_test.go
- pkg/resources/secret.go
- pkg/resources/secret_test.go
- pkg/resources/serviceaccount.go
- pkg/resources/serviceaccount_test.go
- pkg/resources/util.go
This PR adds a generic resource management API that can manage the lifecycle of individual kubernetes resources.
It includes a generic mutator for use case specific kubernetes resources and a list of pre-defined "standard" resources like serviceaccounts, secrets etc. ready to use
Fixes #
```feature user
Generic Kubernetes resource lifecycle api
```
> feat: add generic kubernetest resource management api

- README.md
- go.mod
- go.sum
- pkg/readiness/readinesscheck.go
- pkg/readiness/readinesscheck_test.go
This PR intriduces some helper functionality to detect the readiness of a group of Kubernetes resources:
* Deployments
* Jobs
* Ingresses
* Gateways
Fixes #
```feature user
Readiness check for common Kubernetes resources
```
> feat: add common kubernetes readiness checks

- docs/libs/crds.md
- pkg/crds/crds.go
- pkg/crds/crds_test.go
- pkg/crds/testdata/crd_a.yaml
- pkg/crds/testdata/crd_b.yaml
This PR adds a CRD management API that generalizes code that has been replicated in other repositories.
Fixes #
There is still some CRD coding under `pkg/init/crds` which seems kind of outdated (?) resp. unused by other projects.
We need to discuss what to do with that.
```feature operator
Add CRD management API 
```
> feat: add crd management library

- docs/libs/resource.md
- pkg/crds/crds.go
- pkg/resources/clusterrole.go
- pkg/resources/clusterrole_test.go
- pkg/resources/clusterrolebinding.go
- pkg/resources/clusterrolebinding_test.go
- pkg/resources/configmap.go
- pkg/resources/configmap_test.go
- pkg/resources/crd.go
- pkg/resources/crd_test.go
- pkg/resources/metadata.go
- pkg/resources/metadata_test.go
- pkg/resources/mutator.go
- pkg/resources/mutator_test.go
- pkg/resources/namespace.go
- pkg/resources/namespace_test.go
- pkg/resources/role.go
- pkg/resources/role_test.go
- pkg/resources/rolebinding.go
- pkg/resources/rolebinding_test.go
- pkg/resources/secret.go
- pkg/resources/secret_test.go
- pkg/resources/serviceaccount.go
- pkg/resources/serviceaccount_test.go
The metadata mutator can now also set finalizers and owner references.
Note that the interface changed slightly and implementations outside this repo need to be adapted.
I also moved the labels and annotations, which have previously be present in every pre-defined mutator's constructor, into the metadata mutator.
> expand metadata mutator for finalizers and owner references

- pkg/resources/mutator.go
With this change, `client.DeleteOptions` and `client.GetOptions` are supported in the `DeleteResource` and `GetResource` methods of the resources package.
Possible use case: the options can be used to specify a PropagationPolicy for a delete operation, so that for example the deletion of a Job leads to the deletion of its Pods.
Fixes #
```feature developer
- Support for client.DeleteOptions and client.GetOptions.
```
> feat: delete and get options

- pkg/testing/complex_environment.go
- pkg/testing/environment.go
- pkg/testing/matchers/maybematch.go
Adds two functionalities to the testing library:
- The (Complex)Environment can now be instructed to inject UIDs into k8s objects, which the fake client doesn't do by default.
- Further methods have been added to match the error returned by a failed reconciliation, which was not possible with the `ShouldNotReconcile` function (and its relatives) before.
Required for https://github.com/openmcp-project/openmcp-operator/pull/67
Required for https://github.com/openmcp-project/mcp-operator/pull/103
Refactored out of #66 
```feature developer
The testing library's `ComplexEnvironment` and `Environment` types can now be configured to add UIDs to created resources (the …
```
> extend testing library

- pkg/clusters/cluster.go
The `Scheme()` method of the `Cluster` type did return `nil`, if the internal `cluster.Cluster` was nil, even if the internal `client.Client` was not and returning a scheme would have been possible. The `NewTestClusterFromClient` constructor which can be used to construct a 'fake' `Cluster` for testing purposes returns exactly a `Cluster` instance where the internal `cluster.Cluster` is nil, but the internal `client.Client` is not.
The old implementation of the `Scheme` method therefore prevents any code from using it if said code is being tested with a `Cluster` constructed with the `NewTestClusterFromClient` function.
This PR fixes the problem by returning the internal `client.Client`'s scheme as a fallback, if the internal `cluster.Cluster` is …
> fix cluster's Scheme() method in test setups

- docs/libs/status.md
- pkg/conditions/conditions.go
- pkg/conditions/updater.go
- pkg/conditions/updater_test.go
- pkg/controller/openmcp.go
- pkg/controller/status_updater.go
- pkg/controller/status_updater_test.go
- pkg/controller/testdata/test-02/co_status.yaml
- pkg/testing/matchers/conditions.go
- pkg/testing/matchers/conditions_test.go
- pkg/testing/matchers/suite_test.go
We decided that all our resources should use the `k8s.io/apimachinery/pkg/apis/meta/v1.Condition` type to display conditions. This PR adapts the condition updater to work with this type instead of using our own `Condition` interface.
None, loosely related to https://github.com/openmcp-project/openmcp-operator/issues/70
```breaking developer
⚠️ The condition updater now uses the `Condition` type from the `k8s.io/apimachinery/pkg/apis/meta/v1` package.
```
> Adapt condition updater to use metav1.Condition

- docs/libs/status.md
- pkg/conditions/updater.go
- pkg/conditions/updater_test.go
- pkg/controller/status_updater.go
It is now possible to have the condition updater automatically record events for changed conditions.
None
Requires #86 to be merged first.
```feature developer
Via its `WithEventRecorder` and `Record` methods, the condition updater can now be instructed to record events for changed conditions. The feature can also be enabled by using the status updater's `WithConditionEvents` method.
```
> feat: event recording for changed conditions

- pkg/collections/maps/utils.go
- pkg/collections/maps/utils_test.go
Adds utility functions for checking if a map is a superset of another map.
None
```feature developer
The `pkg/collections/maps` package now has a `ContainsKeysAndValues` function that checks whether a given map is a superset of another map, meaning all keys of the second map also exist in the first one and they have the same values. There is also a `ContainsKeysAndValuesFunc` function that allows to pass in a custom equality function for the value comparison and a `ContainsKeys` function that checks only for keys and ignores values.
```
> feat: add map containment utility functions

- docs/README.md
- docs/libs/smartrequeue.md
- pkg/controller/smartrequeue/context.go
- pkg/controller/smartrequeue/context_test.go
- pkg/controller/smartrequeue/dummyobjects_test.go
- pkg/controller/smartrequeue/entry.go
- pkg/controller/smartrequeue/entry_test.go
- pkg/controller/smartrequeue/example_test.go
- pkg/controller/smartrequeue/store.go
- pkg/controller/smartrequeue/store_test.go
Moved the smartrequeue implementation from the kind clusterprovider into the library.
None
I renamed `Stable` and `Progressing` to `Backoff` and `Reset` to more universally fit the context.
```feature developer
The `pkg/controller/smartrequeue` package was added. It contains utilities for requeuing reconcile requests with an increasing backoff time in between reconciliations, similarly to what the controller-runtime does for reconciliation errors.
```
> move smartrequeue lib from kind clusterprovider

- pkg/clusteraccess/access.go
- pkg/clusteraccess/access_test.go
Adds a helper function to generate an OIDC-based kubeconfig for human users.
Fixes #
```feature developer
The `pkg/clusteraccess` package now contains a `CreateOIDCKubeconfig` function that can be used to generate a kubeconfig that uses the `oidc-login` kubectl plugin to authenticate via OIDC.
```
> feat: add function to generate oidc-based kubeconfig

- go.mod
- pkg/controller/hash.go
- pkg/controller/hash_test.go
This PR adds new functions to generate a hash (in UUID v8 format) for Kubernetes resource names. It uses SHAKE128 (SHA-3) internally which is FIPS 202 compliant.
```feature user
feat: new hash function for k8s resource names
```
> feat: new hash function for k8s resource names

- pkg/crds/crds.go
- pkg/crds/crds_test.go
- pkg/crds/testdata/crd_c.yaml
Enables skipping Clusters when applying CRDs via the CRD management.
Loosely related to https://github.com/openmcp-project/backlog/issues/210
```feature developer
It is now possible to skip Clusters when using the CRD Management to create/update CRDs.
```
> feat: enable skipping clusters in CRD management

- pkg/conditions/updater.go
- pkg/conditions/updater_test.go
We use the k8s default `Condition` type, which not only requires a non-empty `Reason`, but also validates it against a regex. To avoid issues, the ConditionUpdater just added a dummy reason if it was empty, for which it used the condition's `Type`. The regex for type and reason differ, though: type allows `.` but not `:`, while for the reason,  it is the other way around.
This PR replaces `.` with `:` when using the type default the condition reason.
Required for https://github.com/openmcp-project/openmcp-operator/pull/115
(not a hard requirement, though, there is a workaround in place)
```bugfix user
The condition updater would produce an invalid dummy reason …
```
> fix: avoid invalid condition reasons

- pkg/controller/hash.go
Adds a constant for the maximum k8s name length. This is useful for the shorten function. Also adds a shorten function that does not return an error, but panics instead.
None
```feature developer
The `pkg/controller` package now has a constant `K8sMaxNameLength` that holds the maximum length for k8s resource names. This is useful in combination with the package's `ShortenToXCharacters` function.
```
```feature developer
In addition to the `pkg/controller` package's `ShortenToXCharacters` function, there is now also a `ShortenToXCharactersUnsafe` function which panics instead of returning an error if something goes wrong.
```
> feat: add constant for k8s max name length

- pkg/controller/predicates.go
- pkg/controller/predicates_test.go
Adds a predicate that allows to filter for a specific name and namespace. Might be useful for some of our providers that read only a single provider configuration resource.
None
```feature developer
The `pkg/controller` library now has an `ExactNamePredicate` that allows to filter for a specific name and namespace.
```
> feat: add exact name predicate

- pkg/controller/predicates.go
- pkg/controller/predicates_test.go
Adds predicates that allow to filter for specific event types.
None
```feature developer
The `pkg/controller` library now contains the following new predicates:
- OnCreatePredicate() reacts only on create events
- OnDeletePredicate() reacts only on delete events
- OnUpdatePredicate() reacts only on update events
- OnGenericPredicate() reacts only on generic events
- OnEventTypePredicate(eventType) allows to pass in the event type dynamically
```
> feat: add predicates for each specific type of event
